import { Geist, Geist_Mono, Barriecito, Tangerine } from 'next/font/google';
import Navbar from '@/components/navbar';

import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});
const barriecito = Barriecito({
  variable: '--font-barriecito',
  weight: ['400'],
  subsets: ['latin'],
  preload: false,
});

const tangerine = Tangerine({
  variable: '--font-lavishly-yours',
  weight: ['400'],
  subsets: ['latin'],
  preload: false,
});
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable}  ${barriecito.variable} ${tangerine.variable}`}
      >
        <Navbar />
        <main>{children}</main>
      </body>
    </html>
  );
}
