import { Geist, Geist_Mono, Barriecito } from 'next/font/google';
import Link from 'next/link';

import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});
const barriecito = Barriecito({
  variable: '--font-barriecito',
  weight: ['400'],
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable}  ${barriecito.variable}`}
      >
        <nav>
          <Link href="/">Home</Link>
        </nav>
        <main>{children}</main>
      </body>
    </html>
  );
}
